### ISSUE TITLE
Clipped Text and Large Key

### ISSUE THREAD

**Issue by allenbarnett5** [jkriege2/JKQtPlotter#99] opened 2023-08-19 15:34 UTC
Hi Jan: I'm really impressed by JKQtPlotter. It's a lot of work! I have a couple of small problems perhaps you could help me with. This is a window using QGridLayout to place the plots.

![image](https://github.com/jkriege2/JKQtPlotter/assets/6075101/a296e13c-237f-48b8-a3cb-1ded2d154a5f)

 - In the left plot, the right-most x-axis label ("15") is clipped. Resizing the window with the mouse doesn't change it.
 - In the lower right plot, the key seems to have a lot of extra space at the bottom.

I'm using a self-compiled version of Qt 6.5.0 on Pop!_OS. I tried to build my program with the default Qt on Pop, Qt 6.2, but I guess I'm using Qt 6.5 specific classes. If it's helpful, I can reduce my code to a simpler test.

And a question: My plots use JKQTPXFunctionLineGraph for equations which don't really have bounds; I just pick an initial range which is meaningful (just for example: say 1 cycle of cos). "Zoom All" doesn't seem to work to restore the plot to its original size. Is there a function to limit the Zoom range to a fixed size?

Thanks,
Allen

**Comment by jkriege2** [comment] 2023-08-20 08:12
Hi!

Nice to hear that you like the library!

About the tick label clipping: I will have to think about how to fix that (either shift label or allow for more space on the right). Until then you can maybe use JKQTBasePlotter::setPlotBorderRight() to add more free space in the right (https://jkriege2.github.io/JKQtPlotter/class_j_k_q_t_base_plotter.html#af57d78391045d758bb2c725731cfc837).

The keys/legends is one of the areas, the lib is still lacking and that are up for a rework soon ... I think there is not much you can do now, unless you want to look into the layout code in JKQTBasePlotter ...

I deactivated the autozoom of JKQTPXFunctionLineGraph recently, as that didn't really work (hen and egg problem) ... although I might have to look into this further.

You can use JKQTBasePlotter::setAbsoluteXY() and its cousins to limit the max plot range.

Hope that helps!

Best,
Jan

**Comment by allenbarnett5** [comment] 2023-08-22 23:11
That looks great. Thanks!

I looked over the code to draw the key. I was wondering if using
QTextDocument to do the layout would reduce the need for all the explicit
dimension calculations? (I was reflecting on my own code to do something
similar and found QTextDocument did most of the work.)

Allen

**Comment by jkriege2** [comment] 2023-08-23 12:16
About the key drawing: the problem is, that QTextDocument is not really compatible with the Latex-renderer used to layout all the text elements ...

**Comment by jkriege2** [comment] 2023-08-24 20:13
OK, the large key issue should be solved via https://github.com/jkriege2/JKQtPlotter/commit/134739c5a5b072f648064ceb9f9f30f6b68ff750

Can you confirm? Then I'll close this PR!

**Comment by jkriege2** [comment] 2023-08-24 21:31
You are very welcome!

... and thanks fpr the praise :-)))

**Closed by jkriege2** 2023-08-24 21:31 UTC
Labels: bug, Confirmed Bug
