### ISSUE TITLE
Symbol tickness differs in actual plot and legend

### ISSUE THREAD

**Issue by sim186** [jkriege2/JKQtPlotter#73] opened 2022-06-29 09:14 UTC
Hi,

I just notices that the tickness of the symbol into the label is less ticker than the one in the actual plot. Is there a way to change it? I cannot find a function to interact with it.
<img width="905" alt="image" src="https://user-images.githubusercontent.com/18590835/176399759-56ea8f75-96b3-48d2-808e-69b68ff17e7d.png">

**Comment by jkriege2** [comment] 2022-07-01 17:53
Hi!

thanks for reporting ... I'll look into it ... I'm not yet decided whether to treat this as a bug or a feature ... I'll let you know!

Best,
JAN

**Comment by jkriege2** [comment] 2022-08-25 10:25
OK ... I had time to look into this now ... I pressume you're using JKQTPXYParametrizedScatterGraph for you scatter-plot ... So this is what I have to say:
1. If you don't need a parametrization of the symbols, you can simply use JKQTPXYLineGraph, with setDrawLines(false). The latter one is way faster!
2. yes there is some scaling for drawing the symbols in the legend-keys, so if they are way too thick, the line-width is scaled, so they fit in the available space .... If they fit,no scaling is applied!
3. ... BUT: there was a bug in the scaling in JKQTPXYParametrizedScatterGraph, but not in JKQTPXYLineGraph, which I will fix shortly! 

I'll let you know when the problem is solved!

**Comment by jkriege2** [comment] 2022-08-30 07:43
Now  the scaling of symbol-sizes and line-widths in the key is controlled centrally by a few functions. The symbol thickness is used as in the plot, as long as it is <0.3*min(rect.width,rect.height), the symbols have to be smaller than 0.9*min(rect.width,rect.height) and the line-width has to be <0.4*min(...).

Here are two examples:
![scatter_error](https://user-images.githubusercontent.com/11967523/187376582-3588cf48-1853-4962-a302-2b0385b35cf4.png)
![paramscatterplot](https://user-images.githubusercontent.com/11967523/187377917-657e120e-dca5-4900-b0f4-c373c5140676.png)


The fixes are implemented here:
- JKQTPGraphSymbolStyleMixin::getKeySymbolLineWidthPx()
- JKQTPGraphSymbolStyleMixin::getKeySymbolSizePx()
- JKQTPGraphLineStyleMixin::getKeyLinePen()

Hope that solves your problem.

BTW: I also added a JKQTPXYScatterGraph, which is simpler than JKQTPXYLineGraph and JKQTPXYParametrizedScatterGraph ... if that is of interest for you.

**Comment by jkriege2** [comment] 2022-08-30 07:46
fixed via https://github.com/jkriege2/JKQtPlotter/commit/889f95e7af05d4c0fd2bea23109cf0e3bfe7c43a

**Closed by jkriege2** 2022-08-30 07:46 UTC
Labels: bug, question, Confirmed Bug

**Comment by sim186** [comment] 2022-09-04 13:57
Perfect. I will try it out also this one.

Thanks!
