### ISSUE TITLE
MSVC builds fail on Appveyor

### ISSUE THREAD

**Issue by certik** [jkriege2/JKQtPlotter#27] opened 2019-11-18 21:24 UTC
Currently all MSVC builds fail on Appveyor with:
```
C:\projects\jkqtplotter\lib\jkqtplotter\jkqtpdatastorage.cpp(419): error C2589: '(': illegal token on right side of '::' [C:\projects\jkqtplotter\build\lib\jkqtplotter\JKQTPlotterSharedLib.vcxproj]
C:\projects\jkqtplotter\lib\jkqtplotter\jkqtpdatastorage.cpp(419): error C2062: type 'unknown-type' unexpected [C:\projects\jkqtplotter\build\lib\jkqtplotter\JKQTPlotterSharedLib.vcxproj]
```
Here is an example: https://ci.appveyor.com/project/jkriege2/jkqtplotter/builds/28944823/job/wyrb933f0pgr4de8.

**Comment by jkriege2** [comment] 2019-11-21 07:06
That seems to happen, because the /DNOMINMAX definition somehow got lost for MSVC ... I just readded it, but will have to find a better way to deal with such things (which are really messy thanks to M$) ... so let's keep this open until the problem is properly solved ...

Best, JAN

PS: My fixing commit (for now) is https://github.com/jkriege2/JKQtPlotter/commit/6d8139e9960c83fd7ea3bf22b247a7c315e8bcd0

**Comment by certik** [comment] 2019-11-21 16:20
Now there is another failure:
```
TestWidgetGraphs.obj : error LNK2019: unresolved external symbol "public: static struct QMetaObject const JKQTPFilledCurveXGraph::staticMetaObject" (?staticMetaObject@JKQTPFilledCurveXGraph@@2UQMetaObject@@B) referenced in function "public: __cdecl TestWidgetGraphs::TestWidgetGraphs(class QWidget *)" (??0TestWidgetGraphs@@QEAA@PEAVQWidget@@@Z) [C:\projects\jkqtplotter\build\examples\jkqtplot_test\jkqtplot_test.vcxproj]
C:\projects\jkqtplotter\build\output\Release\jkqtplot_test.exe : fatal error LNK1120: 1 unresolved externals [C:\projects\jkqtplotter\build\examples\jkqtplot_test\jkqtplot_test.vcxproj]
```

https://ci.appveyor.com/project/jkriege2/jkqtplotter/builds/29015221/job/tm8op5d8jxkt87ox?fullLog=true

**Comment by jkriege2** [comment] 2019-11-21 17:37
Hhmmm ... let's see whether https://github.com/jkriege2/JKQtPlotter/commit/265a36bf891bb4d02a03e686e2b8f79e27b7a3bc fixes this next problem ...

**Comment by certik** [comment] 2019-11-21 21:33
Still the same problem. Once the master branch passes all the tests, I suggest you submit patches to master through PRs, and don't merge them until tests pass, so that the master branch always works. Otherwise it breaks my code when I update to master and there is some bug.

**Comment by jkriege2** [comment] 2019-11-24 11:37
Problem fixed with commit https://github.com/jkriege2/JKQtPlotter/commit/29b1c5aa377f03e84029c0c130ef2da842587773

**Closed by jkriege2** 2019-11-24 11:37 UTC
Labels: bug
