### ISSUE TITLE
Multi axes...

### ISSUE THREAD

**Issue by aldricson** [jkriege2/JKQtPlotter#87] opened 2022-10-13 06:22 UTC
Hello,
reading the issues , I unerstood that it's not yet possible to have multi series on the same chart with one (let say horizontal axis) for each serie. Am I right?

This functionnality could be very important at least to my point of view.
I may try to help but I'm quite a noob, so I can't promise I will be able to do it.

A question about axis: I would like to use your plotter with 2 X axis in order to show FFT. The first axis is in FFT  buffer nb points.
The second axis is in Frequencies.

following the doxygen doc I found these 2 classes

JKQTPHorizontalAxis
JKQTPHorizontalIndependentAxis 

But well, I'm stuck, whatever I do there's no bug or crash... But there's no other axis I can see on screen.

I didn't find an example to use these classes.

If you have a short example, your help would be the most welcomed.
Best regards.

**Comment by jkriege2** [comment] 2022-10-14 09:19
Hi!

the two classes you mentioned are for drawing axes ... but there is currently no simple way to add them to the plotter as second axes ... but providing secondary axes is rather high in my todo list for the next release ...

Addidng this option will require several steps though:
1. graphs need to have a reference to the axes they should use ... currently the call getXAxis() and getYAxis() hardcoded
2. then I will have to provide a possibility to add additional axes. These also have to be included in the internal calculation of spacing (they require additional space around the plot window itself) ...

So that is really work that alters the heart of the plotter. 

If you want to contribute there you're welcome though ... but it's maybe not the first project, I would recommend ;-)

One question: How do you want to use the secondary axes:
- completely independent of the first? 
- linked to the first axis via a transformation function (e.g. converting radian to degree or FFT datapoint locations to frequencies)
- Do the graphs have to have the possibility to be drawn with selectable axes or do you draw in the primary system, but want the secondary to make reading of values easier?

Best,
JAN

**Comment by aldricson** [comment] 2022-10-17 07:08
Thx for your response.
I'll try to answer your questions:
For this part of the project, I plan to use the second axis linked to the first, fft points to frequencies. The transformation is rather simple since I implemented an FFT class and I obviously have both the sampling frequency and the fft size, the class return minimum frequency (in my case always near 0 (DC + epsilon), maximum frequency (roughly sampling frequency/2) and the resolution (each point is a step of n hertz).

 So I guess, in this particular case, a completly independant axis can also do the job if it's scaled and show at the right place with the good orientation.

In this case, the second axis is just to make the reading easier.

But very soon, I hope to have the possibility to draw the chart with selectable axes.

And the next step will be beeing able to plot multi line charts, with datas related to others ... let say the density of something, speed of something , and the frequency of something. This is an example. These datas are in the same chart because in this case, let's pretend that a change in one imply a change in the other and I would like a graph to have a visual idea of how these 3 datas sets evolves.  But obviously they did not share the same units neither the same scale. 

So the red line serie should have a red scale axis , while the blue serie may have a blue scale axis. 

I'll give a look at your to do list. 

By the way, your work is already impressive and helpfull, and should be inclued in Qt in addition to or replacing Qtchart. QtChart functionalities  are way too basic (you can do anything with it but you have to do everything), your lib already have many higher level important features.

Congrats, regards.
Aldric

**Comment by delaitre** [comment] 2023-03-15 04:42
This seems like a duplicate of #57 

This being said, I am also very interested in multiple axes (especially Y axes). I often have to plot several curve sharing the same X axis (typically time) but have very different range of values for the Y axis (often with different unit).

Having all the curve share the same axis makes it a lot harder to analyse the data.

The first obvious step would be to be able to add a Y axis on the right side of the plot, but we can also image being able to add several Y axis on the left or the right (or both) if one plots many different things.

I reckon 1 Y axis works for maybe 50% of the use cases (you can use some tricks like changing the axis range when the user click different curve or something right now to help with that). 2 Y axes would probably work for 80% of the use cases. More axes would just be a nice bonus at this point.

Just wondering if you are working on this at all or we shouldn't expect anything before few years? ;p

**Comment by delaitre** [comment] 2023-03-15 04:44
Basically something like: https://stackoverflow.com/questions/44679281/qwtplot-multiple-y-axis

**Comment by jkriege2** [comment] 2023-03-15 15:55
Currently I'm not really working on the lib, as there are other things in real life going on ;-) ... but I plan to come back to this during this year ...

**Comment by jkriege2** [comment] 2023-03-22 11:06
Hi!
I looked into this ... and have a half-working draft. I will commit a first step within the next 1-2 weeks, I hope ... will let you know. It probably will not be complete by then, but workable and with an example ... 

The basics are there, but the problem is e.g. how to deal with zooming, styling, auto-sizing and stuff like that + the current interface is only made for one axis-pair, so I will have to do some tweeks that allow to work with several axes at a low cost and does not break old code  ... so expect changes there after the initial commit. The basic interface should be rather stable (although I won't guarantee that until the next tag ...).

Best,
JAN

**Comment by jkriege2** [comment] 2023-03-22 11:07
BTW: I close the duplicate issue #57 ... all discussion will be done here ...

**Comment by jkriege2** [comment] 2023-03-22 11:14
Plan is as follows:
1. You can add additional secondary axes (and will get kind of a handle to access them)
2. You can tell any plotable object, which axes (by their handle) to use for coordinate transform. 
3. The JKQTPBasePlotter/JKQTPlotter-Interface with function setXY/setGrid/setAbsoluteXY/... etc. will by default affect primary axes only and some of the functions will have options to also affect the secondary axes
4. I will try to handle zooming (mouse-drag/rectangle/wheel) in a natural way for all axes (hope that works)
5. I will also try to make autosizing affecting the used axes only

For adding, you can either add instances of the "normal" JKQTPVerticalAxis/JKQTPHorizontalAxis as secondary axes, or - as a future addition - there will be secondary axes that are derived from another (primary or secondary) axis by a function ... so we cover both the use-cases also present e.g. in matplotlib:
- https://matthewkudija.com/blog/2019/02/13/matplotlib-twin-axes/
- https://matplotlib.org/stable/gallery/subplots_axes_and_figures/secondary_axis.html

**Comment by jkriege2** [comment] 2023-03-22 22:12
This is how it looks
![2023-03-22 23_11_41-1_ Second Y-Axis](https://user-images.githubusercontent.com/11967523/227050147-b4def230-c36e-4d2b-877f-b87498307539.png)

**Comment by jkriege2** [comment] 2023-03-23 12:56
I just pushed a first draft ... example is here: https://github.com/jkriege2/JKQtPlotter/tree/master/examples/second_axis

**Comment by jkriege2** [comment] 2023-06-25 10:48
immplemented

**Closed by jkriege2** 2023-06-25 10:48 UTC
Labels: question, new feature, Feature Request
