### ISSUE TITLE
X axis name affects the length of plot bottom border 

### ISSUE THREAD

**Issue by LucienWon** [jkriege2/JKQtPlotter#40] opened 2020-02-26 03:48 UTC
The length of the x-axis name is positively related to the length of the bottom border of the chart. When the axis name becomes longer, the bottom border also changes, which looks very weird.
For example, you can try below code:
    plotResid->getXAxis()->setAxisLabel("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx axis");

I want to show you my screenshots,but i didn't find the interface to add pictures.

**Comment by jkriege2** [comment] 2020-06-27 12:13
Hi!

thanks for reporting ... and sorry for taking so long to come back to you ... I just tried to recreate the problem, but didn't succeed ... For me it looks like this:

![goodxy](https://user-images.githubusercontent.com/11967523/85921931-12441d80-b880-11ea-8884-1cedd20683b9.png)
![goody](https://user-images.githubusercontent.com/11967523/85921949-2720b100-b880-11ea-85f2-23f7f2369c9a.png)
![goodx](https://user-images.githubusercontent.com/11967523/85921961-39025400-b880-11ea-8038-bdfc01cc5d0d.png)
![goodnone](https://user-images.githubusercontent.com/11967523/85921972-47507000-b880-11ea-8f51-4b8cdc965e6e.png)

so ... for me in all cases the plot geometry stays the same, but if the label does not fit, it is just not completely visible ... could you give me a code example that shows your bug?

best,
JAN

**Comment by jkriege2** [comment] 2020-08-13 10:29
Since the problem could not be clarified or reproduced, I close this PR

**Closed by jkriege2** 2020-08-13 10:29 UTC
Labels: need more info, unclear bugreport
